### ISSUE TITLE
引用tolyui-0.0.3+2编译报错

### ISSUE THREAD

**Issue by ysheaven** [TolyFx/toly_ui#20]
../../../.pub-cache/hosted/pub.flutter-io.cn/tolyui-0.0.3+2/lib/form/autocomplete/toly_autocomplete.dart:215:7: Error: No named parameter with the name 'onTap'.
```
@override
  Widget build(BuildContext context) {
    return wrap(
      Container(
        padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 10),
        decoration: BoxDecoration(color: color, borderRadius: const BorderRadius.all(Radius.circular(4))),
        child: Text(widget.text),
      ),
      onTap: widget.onTap,
    );
  }
```

toly_autocomplete.dart继承tolyui_navigation-0.0.8+10中的HoverActionMix类并调用wrap函数，然而wrap形参并没有onTap

**Comment by toly1994328** [comment]
已处理，0.0.3+3
